In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
cf = pd.read_csv(r"C:\Users\priya\Desktop\PyCh_Pro\Churn_Analysis_and_Modelling\data\raw\telco_churn.csv")

In [3]:
cf.sample(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
2034,9720-JJJOR,Male,0,Yes,Yes,41,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,Yes,Bank transfer (automatic),60.30,2511.3,No
4072,2688-BHGOG,Male,1,No,No,9,Yes,No,Fiber optic,No,...,No,No,No,Yes,Month-to-month,Yes,Electronic check,79.55,718.55,No
2089,3933-DQPWX,Female,0,No,No,50,No,No phone service,DSL,No,...,Yes,Yes,No,No,Two year,No,Credit card (automatic),39.70,1932.75,No
5291,1334-PDUKM,Female,0,Yes,No,68,Yes,Yes,Fiber optic,No,...,Yes,No,No,No,One year,No,Credit card (automatic),86.45,5762.95,No
3858,0840-DCNZE,Male,0,No,No,47,Yes,No,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Bank transfer (automatic),86.95,4138.9,No

In [4]:
cf.shape

(7043, 21)

In [5]:
cf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [6]:
cf["gender"] = cf["gender"].astype("category")
cf["Partner"] = cf["Partner"].astype("category")
cf["Dependents"] = cf["Dependents"].astype("category")
cf["PhoneService"] = cf["PhoneService"].astype("category")
cf["MultipleLines"] = cf["MultipleLines"].astype("category")
cf["InternetService"] = cf["InternetService"].astype("category")
cf["OnlineSecurity"] = cf["OnlineSecurity"].astype("category")
cf["OnlineBackup"] = cf["OnlineBackup"].astype("category")
cf["DeviceProtection"] = cf["DeviceProtection"].astype("category")
cf["TechSupport"] = cf["TechSupport"].astype("category")
cf["StreamingTV"] = cf["StreamingTV"].astype("category")
cf["StreamingMovies"] = cf["StreamingMovies"].astype("category")
cf["Contract"] = cf["Contract"].astype("category")
cf["PaperlessBilling"] = cf["PaperlessBilling"].astype("category")
cf["PaymentMethod"] = cf["PaymentMethod"].astype("category")
cf["Churn"] = cf["Churn"].astype("category")

In [7]:
cf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   category
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   category
 4   Dependents        7043 non-null   category
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   category
 7   MultipleLines     7043 non-null   category
 8   InternetService   7043 non-null   category
 9   OnlineSecurity    7043 non-null   category
 10  OnlineBackup      7043 non-null   category
 11  DeviceProtection  7043 non-null   category
 12  TechSupport       7043 non-null   category
 13  StreamingTV       7043 non-null   category
 14  StreamingMovies   7043 non-null   category
 15  Contract          7043 non-null   category
 16  PaperlessBilling  7043 non-null   category
 17  PaymentMethod     7043 non-null   category
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   category
dtypes: category(16), float64(1), int64(2), object(2)
memory usage: 387.4+ KB

In [35]:
cf.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [11]:
cf.drop(columns = ["customerID", "TotalCharges"], inplace = True)

### Preprocessing Starts...

In [17]:
#train test split is not done because, it shuffles the data due to which time series data simulation gets hindered
n = cf.shape[0]
train_end = int(0.70 * n)
test_end = int(0.85 * n)

In [30]:
X_train = cf.iloc[:train_end].drop(columns = ["Churn"])
y_train = cf.iloc[:train_end]["Churn"]
X_test = cf.iloc[train_end:test_end].drop(columns = ["Churn"])
y_test = cf.iloc[train_end:test_end]["Churn"]
X_stream = cf.iloc[test_end:].drop(columns = ["Churn"])
y_stream = cf.iloc[test_end:]["Churn"]

In [41]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train[["tenure", "MonthlyCharges"]])
scaled_num_train = scaler.transform(X_train[["tenure", "MonthlyCharges"]])
scaled_num_test = scaler.transform(X_test[["tenure", "MonthlyCharges"]])

In [34]:
scaler.mean_

array([32.33711968, 64.85382353])

In [51]:
scaled_train_cf = pd.DataFrame(
    scaled_num_train,
    columns=["tenure", "MonthlyCharges"],
    index=X_train.index
)
X_train[["tenure", "MonthlyCharges"]] = scaled_train_cf

In [52]:
X_train[["tenure", "MonthlyCharges"]]

        tenure  MonthlyCharges
0    -1.272240       -1.161465
1     0.067510       -0.262257
2    -1.231642       -0.365119
3     0.514094       -0.748360
4    -1.231642        0.193982
...        ...             ...
4925  1.285466        1.448227
4926  1.204269       -0.156078
4927 -0.094884       -1.519820
4928 -1.150445       -0.625590
4929  1.244867        0.635291

[4930 rows x 2 columns]

In [47]:
X_train.index

RangeIndex(start=0, stop=4930, step=1)

In [54]:
scaled_test_cf = pd.DataFrame(
    scaled_num_test,
    columns =["tenure", "MonthlyCharges"],
    index = X_test.index
)
X_test[["tenure", "MonthlyCharges"]] = scaled_test_cf

In [55]:
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, LabelEncoder

In [56]:
cf.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'Churn'],
      dtype='object')

In [59]:
cf.sample(5)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,Churn
5692,Male,0,Yes,Yes,9,Yes,No,DSL,No,Yes,No,Yes,No,No,Month-to-month,No,Mailed check,54.80,No
3037,Male,0,No,No,32,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,No,Credit card (automatic),20.35,No
3583,Male,0,Yes,Yes,40,No,No phone service,DSL,No,Yes,Yes,Yes,Yes,Yes,One year,No,Mailed check,60.30,No
6989,Female,0,Yes,Yes,20,Yes,Yes,DSL,Yes,No,No,No,Yes,Yes,One year,No,Bank transfer (automatic),76.00,No
1472,Male,0,Yes,Yes,13,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Credit card (automatic),74.40,Yes

NameError: name 'df' is not defined